<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup Label="Configuration">
    <SignAssembly>True</SignAssembly>
    <DelaySign>False</DelaySign>
    <RootNamespace />
  </PropertyGroup>
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationIcon />
    <OutputTypeEx>library</OutputTypeEx>
    <StartupObject />
    <AssemblyName>itext.pdfocr.api.tests</AssemblyName>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>itext.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="itext.snk" />
  </ItemGroup>
  <PropertyGroup>
    <NoWarn>1701;1702;1591;1570;1572;1573;1574;1580;1584;1658</NoWarn>
    <!-- TODO DEVSIX-9075: remove this suppression -->
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\itext\itext.pdfocr.api\itext.pdfocr.api.csproj" />
    <PackageReference Include="itext.pdftest" Version="9.8.0-SNAPSHOT" Condition="!Exists('..\..\..\itextcore\itext\itext.pdftest\itext.pdftest.csproj')" />
    <ProjectReference Include="..\..\..\itextcore\itext\itext.pdftest\itext.pdftest.csproj" Condition="Exists('..\..\..\itextcore\itext\itext.pdftest\itext.pdftest.csproj')" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.8.0-SNAPSHOT" Condition="!Exists('..\..\..\itextcore\itext\itext.bouncy-castle-adapter\itext.bouncy-castle-adapter.csproj')" />
    <ProjectReference Include="..\..\..\itextcore\itext\itext.bouncy-castle-adapter\itext.bouncy-castle-adapter.csproj" Condition="Exists('..\..\..\itextcore\itext\itext.bouncy-castle-adapter\itext.bouncy-castle-adapter.csproj')" />
  </ItemGroup>
</Project>