<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <!-- The .csrpoj file uses ../Directory.Build.props as a source for some configurations -->
  <PropertyGroup>
    <!-- TargetFrameworks property from ../Directory.Build.props is overriden -->
    <TargetFrameworks>net461</TargetFrameworks>
    <AssemblyName>itext.pdfocr.tesseract4</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\itext.pdfocr.api\itext.pdfocr.api.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ContentWithTargetPath Include="lib\Tesseract.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>Tesseract.dll</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="lib\x64\liblept1760.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>x64\liblept1760.dll</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="lib\x64\libtesseract400.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>x64\libtesseract400.dll</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="lib\x86\libtesseract400.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>x86\libtesseract400.dll</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="lib\x86\liblept1760.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>x86\liblept1760.dll</TargetPath>
    </ContentWithTargetPath>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Tesseract">
      <HintPath>lib\Tesseract.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>