<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <!-- The .csrpoj file uses ../Directory.Build.props as a source for some configurations -->
  <PropertyGroup>
    <AssemblyName>itext.pdfocr.api</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="IronSoftware.System.Drawing" Version="2025.6.2" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="itext" Version="9.8.0-SNAPSHOT" Condition="!Exists('..\..\..\itextcore\itext\itext.layout\itext.layout.csproj')" />
    <ProjectReference Include="..\..\..\itextcore\itext\itext.layout\itext.layout.csproj" Condition="Exists('..\..\..\itextcore\itext\itext.layout\itext.layout.csproj')" />
    <ProjectReference Include="..\..\..\itextcore\itext\itext.pdfa\itext.pdfa.csproj" Condition="Exists('..\..\..\itextcore\itext\itext.pdfa\itext.pdfa.csproj')" />
    <ProjectReference Include="..\..\..\itextcore\itext\itext.styledxmlparser\itext.styledxmlparser.csproj" Condition="Exists('..\..\..\itextcore\itext\itext.styledxmlparser\itext.styledxmlparser.csproj')" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="resources\com\itextpdf\ocr\fonts\LiberationSans-Regular.ttf">
        <LogicalName>iText.Pdfocr.Api.font.LiberationSans-Regular.ttf</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>