<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <!-- The .csrpoj file uses ../Directory.Build.props as a source for some configurations -->
  <PropertyGroup>
    <AssemblyName>itext.pdfocr.onnx.cpu</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.22.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\itext.pdfocr.onnx.abstract\itext.pdfocr.onnx.abstract.csproj" />
  </ItemGroup>
</Project>