<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup Label="Configuration">
    <SignAssembly>True</SignAssembly>
    <DelaySign>False</DelaySign>
    <RootNamespace />
    <DocumentationFile>$(TargetDir)bin\$(Configuration)\$(TargetFramework)\itext.pdfocr.onnx.cpu.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net461</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputType>library</OutputType>
    <AssemblyName>itext.pdfocr.onnx.cpu</AssemblyName>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>itext.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <NoWarn>CS1591;CS1570;CS1572;CS1573;CS1574;CS1580;CS1584;CS1658</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.22.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\itext.pdfocr.onnx.abstract\itext.pdfocr.onnx.abstract.csproj" />
  </ItemGroup>
</Project>