<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
    <!-- The .csrpoj file uses ../Directory.Build.props as a source for some configurations -->
    <PropertyGroup>
        <!-- TargetFrameworks property from ../Directory.Build.props is overriden -->
        <TargetFrameworks>net461</TargetFrameworks>
        <AssemblyName>itext.pdfocr.tesseract4.tests</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="System.Drawing" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\itext\itext.pdfocr.tesseract4\itext.pdfocr.tesseract4.csproj" />
        
        <PackageReference Include="itext.pdftest" Version="9.8.0-SNAPSHOT" Condition="!Exists('..\..\..\itextcore\itext\itext.pdftest\itext.pdftest.csproj')" />
        <ProjectReference Include="..\..\..\itextcore\itext\itext.pdftest\itext.pdftest.csproj" Condition="Exists('..\..\..\itextcore\itext\itext.pdftest\itext.pdftest.csproj')" />
        
        <PackageReference Include="itext.bouncy-castle-adapter" Version="9.8.0-SNAPSHOT" Condition="!Exists('..\..\..\itextcore\itext\itext.bouncy-castle-adapter\itext.bouncy-castle-adapter.csproj')" />
        <ProjectReference Include="..\..\..\itextcore\itext\itext.bouncy-castle-adapter\itext.bouncy-castle-adapter.csproj" Condition="Exists('..\..\..\itextcore\itext\itext.bouncy-castle-adapter\itext.bouncy-castle-adapter.csproj')" />
    </ItemGroup>
    <ItemGroup>
        <Reference Include="Tesseract">
            <HintPath>..\..\itext\itext.pdfocr.tesseract4\lib\Tesseract.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>